### ISSUE TITLE
Python2 chokes on unicode

### ISSUE THREAD

**Issue by Changaco** [Changaco/python-etherpad_lite#6]
Reported by @marcellmars in #5.

```
% python2 -c "from urllib import urlencode; r = urlencode(dict(foo=u'à')); print(type(r), r, r.encode('ascii'))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/urllib.py", line 1347, in urlencode
    v = quote_plus(str(v))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
```

I see two possible solutions: encode the values to utf8 ourselves, or switch to [requests](https://pypi.python.org/pypi/requests).

**Comment by Changaco** [comment]
I've uploaded a 0.5 release to PyPI containing the fix for this issue.
